### ISSUE TITLE
Poles stucked in ground

### ISSUE THREAD

**Issue by WURS5000** [ravmustang/eXpoch_VectorBuilding_lite#1]
Hey, 

i noticed that your script causes following error, at least on chernarus:

If you setup a a new pole (create territory) the pole will not be created even we the groundlevel, it's like -4 on position_z into the ground. You'r also not able to raise it via page up

**Comment by WURS5000** [comment]
ah, sorry - saw you already fixed it 👍

**Comment by ravmustang** [comment]
No problem WURS5000, thanks for taking a second look to see the fixes 👍
